### ISSUE TITLE
KeyCode ENUM value for KeyDown has same value as KeyUp (84)

### ISSUE THREAD

**Issue by MaaxGyver** [sub-c/AllegroDotNet#21]
It looks like the KeyCode enum vale for KeyDown has the same value as KeyUp, which is 84.  Just guessing it should be 85.  At least in my code, I updated it to be 85 and all seemed to work well.

```
    /// <summary>
    /// Up key.
    /// </summary>
    KeyUp = 84,

    /// <summary>
    /// Down arrow key.
    /// </summary>
    KeyDown = 84, <-- Should be 85
```

**Comment by sub-c** [comment]
Thanks for the bug report.
Fixed in v0.7.10.
https://github.com/sub-c/AllegroDotNet/releases/tag/v0.7.10
https://www.nuget.org/packages/SubC.AllegroDotNet/0.7.10
